# Generated by Django 6.0.1 on 2026-08-24 13:09

import sorl.thumbnail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='background_image',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='backgrounds/'),
        ),
    ]
